name: 'superligaen'
version: '1.0.0'
profile: 'superligaen'

model-paths: ["models"]
seed-paths:  ["seeds"]
test-paths:  ["tests"]
macro-paths: ["macros"]

seeds:
  superligaen:
    +schema: gold
    referee_id_overrides:
      +column_types:
        referee_id: integer
        canonical_referee_id: integer

models:
  superligaen:
    +post_hook: "{{ cleanup_dbt_backup() }}"
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
