superligaen:
  target: local
  outputs:
    local:
      type: duckdb
      path: "../local_dev.duckdb"
      schema: silver
    prod:
      type: duckdb
      path: "md:superligaen"
      schema: silver
