{{
    config(
        materialized='incremental',
        incremental_strategy='delete+insert',
        unique_key=['season', 'league_id', 'player_id']
    )
}}

SELECT
    season,
    league_id,
    (elem->>'$.player.id')::INTEGER              AS player_id,
    elem->>'$.player.name'                       AS player_name,
    elem->>'$.player.firstname'                  AS firstname,
    elem->>'$.player.lastname'                   AS lastname,
    (elem->>'$.player.age')::INTEGER             AS age,
    elem->>'$.player.birth.date'                 AS birth_date,
    elem->>'$.player.birth.place'                AS birth_place,
    elem->>'$.player.birth.country'              AS birth_country,
    elem->>'$.player.nationality'                AS nationality,
    elem->>'$.player.height'                     AS height,
    elem->>'$.player.weight'                     AS weight,
    (elem->>'$.player.injured')::BOOLEAN         AS injured,
    elem->>'$.player.photo'                      AS photo,
    (stats->>'$.team.id')::INTEGER               AS team_id,
    stats->>'$.team.name'                        AS team_name,
    stats->>'$.team.logo'                        AS team_logo,
    (stats->>'$.games.appearences')::INTEGER     AS appearances,
    (stats->>'$.games.lineups')::INTEGER         AS lineups,
    (stats->>'$.games.minutes')::INTEGER         AS minutes,
    (stats->>'$.games.number')::INTEGER          AS shirt_number,
    stats->>'$.games.position'                   AS position,
    stats->>'$.games.rating'                     AS rating,
    (stats->>'$.games.captain')::BOOLEAN         AS captain,
    (stats->>'$.substitutes.in')::INTEGER        AS sub_in,
    (stats->>'$.substitutes.out')::INTEGER       AS sub_out,
    (stats->>'$.substitutes.bench')::INTEGER     AS sub_bench,
    (stats->>'$.shots.total')::INTEGER           AS shots_total,
    (stats->>'$.shots.on')::INTEGER              AS shots_on,
    (stats->>'$.goals.total')::INTEGER           AS goals,
    (stats->>'$.goals.conceded')::INTEGER        AS goals_conceded,
    (stats->>'$.goals.assists')::INTEGER         AS assists,
    (stats->>'$.goals.saves')::INTEGER           AS saves,
    (stats->>'$.passes.total')::INTEGER          AS passes_total,
    (stats->>'$.passes.key')::INTEGER            AS passes_key,
    stats->>'$.passes.accuracy'                  AS passes_accuracy,
    (stats->>'$.tackles.total')::INTEGER         AS tackles_total,
    (stats->>'$.tackles.blocks')::INTEGER        AS tackles_blocks,
    (stats->>'$.tackles.interceptions')::INTEGER AS interceptions,
    (stats->>'$.duels.total')::INTEGER           AS duels_total,
    (stats->>'$.duels.won')::INTEGER             AS duels_won,
    (stats->>'$.dribbles.attempts')::INTEGER     AS dribbles_attempts,
    (stats->>'$.dribbles.success')::INTEGER      AS dribbles_success,
    (stats->>'$.dribbles.past')::INTEGER         AS dribbles_past,
    (stats->>'$.fouls.drawn')::INTEGER           AS fouls_drawn,
    (stats->>'$.fouls.committed')::INTEGER       AS fouls_committed,
    (stats->>'$.cards.yellow')::INTEGER          AS yellow_cards,
    (stats->>'$.cards.yellowred')::INTEGER       AS yellowred_cards,
    (stats->>'$.cards.red')::INTEGER             AS red_cards,
    (stats->>'$.penalty.won')::INTEGER           AS penalty_won,
    (stats->>'$.penalty.committed')::INTEGER     AS penalty_committed,
    (stats->>'$.penalty.scored')::INTEGER        AS penalty_scored,
    (stats->>'$.penalty.missed')::INTEGER        AS penalty_missed,
    (stats->>'$.penalty.saved')::INTEGER         AS penalty_saved,
    ingested_at
FROM {{ source('bronze', 'api_football__players') }},
UNNEST(raw_json::JSON[]) AS t1(elem),
UNNEST((elem->'$.statistics')::JSON[]) AS t2(stats)
{% if is_incremental() %}
WHERE {{ season_filter() }}
{% endif %}
